var = 8347
print(var)
print(type(var))
var = str(var)
print(var)
print(type(var))
var = float(var)
print(var)
print(type(var))
var = bool(var)
print(var)
print(type(var))
var = complex(var)
print(var)
print(type(var))